### ISSUE TITLE
How to SPP for IOS in Xamarin Forms?

### ISSUE THREAD

**Issue by biapar** [acaliaro/TestBth#2]
How to SPP for IOS in Xamarin Forms?

**Comment by seba47** [comment]
I have researched to get it working but I have not find a solution :( . Also they should be registered Bth in the apple center, if not I don't know you could connect them. Maybe Alessandro know a bit more about that.

**Comment by biapar** [comment]
The problem is that iOS not support SPP or serial connection over BT without certified hardware or MFi program.
