### ISSUE TITLE
EXCEPTION: read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by WillAutioItrax** [acaliaro/TestBth#4]
Hi. I am trying to use this app on an Android phone. I get to:
`await BthSocket.ConnectAsync ();`
and the app throws the following exception:
`EXCEPTION: read failed, socket might closed or timeout, read ret: -1`
Somwhere I saw a reference to SPP mode. Does this only work in that mode? I can only get a Bluetooth connection in HID mode.
Thanks for looking at this!
Will

**Comment by acaliaro** [comment]
If you use HID you don't need bluetooth socket connection. HID output data on the UI control that has focus

**Comment by WillAutioItrax** [comment]
@acaliaro Thanks for the quick reply.
